name: Lokalise

on:
  workflow_dispatch:

jobs:
  lokalise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'
      - name: Setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
          npm ci
      - name: Run Lokalise
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: PATH=`pwd`/bin:${PATH} npm run lokalise
      - name: Cleanup
        run: |
          rm -r bin
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'chore-lokalise'
          commit-message: 'chore: lokalise'
          delete-branch: true
          title: 'chore: lokalise'
